### ISSUE TITLE
Joomla 5 Support

### ISSUE THREAD

**Issue by johanpeters** [gregorionuti/Joomla-Params-Backup#2]
is Joomla 5 supported and if not, any ETA?

greets

**Comment by gregorionuti** [comment]
Hello. Joomla 5 is not supported yet. 
I've launched a [small campaign on ko-fi](https://ko-fi.com/gregorionuti) to buy the tool I need to test the plugin after migration, but not much interest.
Besides that, I'm planning to dedicate time on Params Backup migration, most likely after this summer.

**Comment by johanpeters** [comment]
> Hello. Joomla 5 is not supported yet. I've launched a [small campaign on ko-fi](https://ko-fi.com/gregorionuti) to buy the tool I need to test the plugin after migration, but not much interest. Besides that, I'm planning to dedicate time on Params Backup migration, most likely after this summer.

Okay.. donneted some bugs for you... hope it helps..

**Comment by gregorionuti** [comment]
Just released new update. Now Params Backup is Joomla 3.9+ | 4.0+ | 5.0+ compatible, it works on MySQL 5.7 and on MySQL 8.0.
